# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "849aab16dcfa9b9dd41452a2dda156d3"
name = "render-sample-app"
handle = "render-sample-app-1"
application_url = "https://blocked-defining-maria-legislation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-gareth.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://blocked-defining-maria-legislation.trycloudflare.com/auth/callback",
  "https://blocked-defining-maria-legislation.trycloudflare.com/auth/shopify/callback",
  "https://blocked-defining-maria-legislation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
